### ISSUE TITLE
  does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by THORONGlL** [feliwir/libapt#1]
I'm unable to build the project.  It says:

CMake Error at CMakeLists.txt:14 (add_subdirectory):
  The source directory

    C:/.../libapt-master/deps/glfw

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:16 (add_subdirectory):
  The source directory

    C:/.../libapt-master/deps/libbig

  does not contain a CMakeLists.txt file.

**Comment by feliwir** [comment]
You didn't use "git clone --recursive" probably. So the glfw submodule is missing (and for that matter all other submodules)

**Comment by THORONGlL** [comment]
when looking at the example I get alot of "GL_INVALID_VALUE error generated. Invalid clear bits" when I hover over  anything I can do about that?

**Comment by feliwir** [comment]
What is going on? :D

**Comment by THORONGlL** [comment]
I closed it. Then had a question. Opened it up. Answered my own question and closed it again.  😆
